# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=4096)),
                ('provincia', models.CharField(max_length=30)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('aguapotable', models.BooleanField()),
                ('baños', models.BooleanField()),
                ('restauracion', models.BooleanField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('imei', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sitios',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van2enjoy_app.Tipos'),
        ),
        migrations.AddField(
            model_name='sitios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van2enjoy_app.Usuarios'),
        ),
    ]
