# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitios',
            options={'verbose_name_plural': 'Sitios'},
        ),
        migrations.AlterModelOptions(
            name='tipos',
            options={'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
