# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0002_auto_20161019_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
