# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0003_auto_20161019_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitios',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
