# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0005_auto_20161020_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitios',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
