# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0008_auto_20161020_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitios',
            name='provincia',
        ),
    ]
