# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0017_auto_20161021_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincias',
            name='provincia',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
