# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0019_remove_sitios_provincia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provincias',
        ),
    ]
