# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0025_auto_20161021_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincias',
            options={'ordering': ['provincia'], 'verbose_name_plural': 'Provincias'},
        ),
    ]
