# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0026_auto_20161021_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='alias',
            new_name='nombre',
        ),
    ]
