# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0027_auto_20161026_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van2enjoy_app.Sitios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van2enjoy_app.Usuarios')),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
