# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0028_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sitios')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='van2enjoy_app.Sitios')),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
    ]
