# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:28
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('van2enjoy_app', '0029_fotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotos',
            options={'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterField(
            model_name='fotos',
            name='imagen',
            field=django_resized.forms.ResizedImageField(upload_to='sitios'),
        ),
    ]
